### PR TITLE
Add pgAdmin to Docker Compose

### PR DESCRIPTION
**Pull request by rasmus-unity**
When investigating the `'NoneType' object has no attribute 'family'` error, needed to have easy access to local database for testing.

So decided to add pgAdmin container to Docker Compose setup. After running `docker compose up`, it runs on http://localhost:5050, and gives a graphical interface to local Postgres database:

image

Hope others can find that useful :)

### CODE REVIEW

**Comment by rasmus-unity** [comment]
After talking online this evening, we are concerned if this gets deployed to production. To be sure, we should look into splitting into a pure development Docker Compose file

Perhaps @Rotendahl can confirm if this would get deployed to production?

**Comment by Rotendahl** [comment]
If you want you can also access the database by just installing pgAdmin on your own machine and point it to localhost:5432 as it's exposed in docker-compose. 

But if you want to provide a pre configured pgAdmin to everbody you can just merge it.
It will not be added to prod as only contained configured in [app.json](https://github.com/CodingPirates/forenings_medlemmer/blob/master/app.json) get deployed.

**Review by Rotendahl — APPROVED** [review]
LGTM

**Review by lakridserne — APPROVED** [review]
Based on @Rotendahl's comment, this should be fine to release based on that pgAdmin doesn't touch prod.

**Pull request merged**
